site_name: Code Snippets
docs_dir: /docs/snippets
repo_url: https://gitea.epichouse.co.uk/dan/code-snippets
repo_name: code-snippets

theme:
  name: material
  logo: ../logo.png
  favicon: ../logo.png
  palette:
    - scheme: slate
      primary: black
extra:
  generator: false